### ISSUE TITLE
Add Table method: toArray()

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/array#53]
## What
Add new method to Table class, in src/Table.php file

## Description
The `toArray()` method returns a bidimensional PHP array from Table class.

In `Table` class, you could have something like this:

```
    /**
     * @return array
     */
    public function toArray(): array
    {
        $result = [];
        foreach ($this->rows() as $key => $row ) {
            $result[$key] = $row->arr();
        }
        return $result;
    }
```

## Checklist
- [ ] implement method
- [ ] write phpdoc for the function
- [ ] write test in tests/TableTest.php
- [ ]  execute composer format
- [ ] execute composer test-coverage
- [ ] check if your method has full test coverage
- [ ] add method in changelog
- [ ] update doc/table.md adding a use case of the new method
- [ ] update cheatsheet (examples/cheatsheet-table.php)

**Comment by RoadSigns** [comment]
I think personally for this we should not call it `arr()` since it implies that it's related to the `Arr` object. I think a more fitting name might be `toArray()`.

We can then use this to cover the entire table and all of the `Arr` objects inside of it to an array based format.

We could even then look in the future to adding something like `toJson()` on the Table to get the information encoded.

**Comment by roberto-butti** [comment]
> I think personally for this we should not call it `arr()` since it implies that it's related to the `Arr` object. I think a more fitting name might be `toArray()`.
> 
> We can then use this to cover the entire table and all of the `Arr` objects inside of it to an array based format.
> 
> We could even then look in the future to adding something like `toJson()` on the Table to get the information encoded.

totally agree on the naming. I changed the title and the first comment of the issue.
